insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(1001L,'USD','INR',65,'');
insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(1002L,'EUR','INR',65,'');
insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(1003L,'AUS	','INR',65,'');
